### ISSUE TITLE
ERROR: compilation failed for package ‘gridtext’ with TRAVIS

### ISSUE THREAD

**Issue by TuQmano** [wilkelab/gridtext#11]
I have problems with `{gridtext}` (as a dependency on `{ggtext}`) in the package` {polAr} `compiled in TRAVIS and I cannot resolve the error.

`** package ‘gridtext’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -std=gnu++11 -I"/home/travis/R-bin/lib/R/include" -DNDEBUG  -I'/home/travis/R/Library/Rcpp/include' -I'/home/travis/R/Library/testthat/include' -I/home/travis/R-bin/include   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from gridtext_types.h:12:0,
                 from RcppExports.cpp:4:
grid-renderer.h: In member function ‘void GridRenderer::raster(Rcpp::RObject, Length, Length, Length, Length, bool, const GraphicsContext&)’:
grid-renderer.h:61:94: error: no matching function for call to ‘Rcpp::Vector<10, Rcpp::PreserveStorage>::Vector(int, bool&, const GraphicsContext&)’
           NumericVector(1, width), NumericVector(1, height), LogicalVector(1, interpolate, gp)`

**COMPLETE LOG:** https://travis-ci.org/github/electorArg/polAr/jobs/719017528#L1919

I don't know how to better report this bug. Sorry in advance and thank you!

**Comment by clauswilke** [comment]
You're using trusty as your build environment, which was released in 2014. My guess would be that your C++ compiler is too old. Try using a newer build environment (e.g., xenial) or update your C++ compiler as part of your build and see if that helps.

**Comment by TuQmano** [comment]
Thanks!
It worked perfectly with xenial https://travis-ci.org/github/electorArg/polAr
