### ISSUE TITLE
CRAN update timeline?

### ISSUE THREAD

**Issue by tanho63** [wilkelab/gridtext#21]
Hiya! I was hoping to submit a package to CRAN that depended on a feature that was added in #20 - do you know when the next version of this package will be updated there? 

Thank you so much!

**Comment by guga31bb** [comment]
Also interested in this- thank you!

**Comment by clauswilke** [comment]
Yeah, sorry, I know I need to update on CRAN. I hope I'll find a little bit of free time over the holidays to get this done.

**Comment by saiemgilani** [comment]
Well I'll save these memes I made then. Appreciate the response!

**Comment by bwiernik** [comment]
Hey @clauswilke I just found that the CRAN version of gridtext is producing improperly kerned text in R 4.2 when `plot.title = element_markdown(face = "bold")`. The github version fixes this, but many of the systems in my org can only install from CRAN, not GitHub. That's breaking a bunch of themes used on my team. Is there anything I could do to help get gridtext submitted to CRAN?

**Comment by clauswilke** [comment]
@bwiernik Yeah, I know, it needs updating. I have been super busy lately and just never get around to submitting it to CRAN. Realistically, if somebody motivated wanted to take over maintainership that might help. I don't see myself working much on this particular package in the foreseeable future and would be happy to hand it over to somebody who is more on top of things.

**Comment by bwiernik** [comment]
@clauswilke I'd be happy to handle the CRAN admin stuff if you're open to answering my technical questions about *grid* when they come up

**Comment by clauswilke** [comment]
Ok, how should we proceed? Should I give you write access to this repo? This will allow you to do everything you need to do, I think, including updating the web page (since it's hosted from this repo). There's also the ggtext package, which probably should go hand-in-hand (even though I don't think it needs updating at this time).

I'm happy to answer questions or otherwise help out. I just don't have a lot of time to put towards this in terms of developing new features and/or dealing with staying on top of CRAN issues.

**Comment by bwiernik** [comment]
Sure, if you give me write access to the two repos, I can update the maintainer and submit the update the CRAN

**Comment by bwiernik** [comment]
@clauswilke i submitted the packages to CRAN. When you have a moment, could you respond to the Maintainer Change emails you received from CRAN?

**Comment by clauswilke** [comment]
I did already do that this morning. Did it not work?

**Comment by bwiernik** [comment]
It worked now worries. Both packages on their way to cran

**Comment by guga31bb** [comment]
Thank you for getting this done!
