### ISSUE TITLE
latex bar

### ISSUE THREAD

**Issue by kongdd** [wilkelab/gridtext#27]
Any idea how to add latex bar in gridtext?
<https://stackoverflow.com/questions/32427508/how-to-add-barx-to-an-r-plot>

**Comment by bwiernik** [comment]
Use the unicode character `"\u0305"`

https://www.fileformat.info/info/unicode/char/0305/index.htm

**Comment by kongdd** [comment]
How about \vec{x}? It seems that unicode character "\u0305" not work in that situation.

**Comment by bwiernik** [comment]
U+20D7 COMBINING RIGHT ARROW ABOVE

All of these symbols are present in Unicode. Use the appropriate combining Unicode characters
