### ISSUE TITLE
centering text does not work when cex is unequal to 1

### ISSUE THREAD

**Issue by markheckmann** [wilkelab/gridtext#28]
I am having a hard time centering text in a `textbox_grob` when `cex <> 1`. Setting `halign = .5` only appears to center text with `gp = gpar(cex = 1)`. When `cex <> 1`, the text is left aligned at the same starting position as if `cex = 1` (see image below).

Currently, I am unable to figure out how to center text with `cex <> 1`.  In case all this is expected behavior, it is somewhat unintuitive, at least for me. 🙈

*PS*: Thanks for your efforts in building `gridtext`! 👍👍👍

```{r}
library(grid)
library(gridtext)

grid.newpage()

vp = viewport(y = .6, width = unit(3, "cm"))
g <- textbox_grob(text = "Centered?", halign = 0.5,
                  gp = gpar(cex = 1.2), box_gp = gpar(col = "red"), vp = vp)
grid.draw(g)

vp = viewport(y = .5, width = unit(3, "cm"))
g <- textbox_grob(text = "Centered!", halign = 0.5,
                  gp = gpar(cex = 1), box_gp = gpar(col = "red"), vp = vp)
grid.draw(g)

vp = viewport(y = .4, width = unit(3, "cm"))
g <- textbox_grob(text = "Centered?", halign = 0.5,
                  gp = gpar(cex = .9), box_gp = gpar(col = "red"), vp = vp)
grid.draw(g)

vp = viewport(y = .3, width = unit(3, "cm"))
g <- textbox_grob(text = "Centered?", halign = 0.5,
                  gp = gpar(cex = .7), box_gp = gpar(col = "red"), vp = vp)
grid.draw(g)
```
![image](https://user-images.githubusercontent.com/152927/194942669-0d4a458e-6c2d-4052-8edb-1d063e504a23.png)

**Comment by clauswilke** [comment]
I'm pretty sure `cex` values other than 1 are not supported. I don't remember exactly why, but I suspect there was a technical reason. But could also have been opinionated design choice. I've always felt that the `cex` parameter is a design flaw in the R graphics engine. It creates unnecessary complexity without solving a real problem.

If you want a bigger font, just increase the font size.

**Comment by markheckmann** [comment]
Thanks. Makes sense. I will avoid `cex` altogether.
