### ISSUE TITLE
richtext_grob outputs an error when the text is empty

### ISSUE THREAD

**Issue by lepennec** [wilkelab/gridtext#5]
Hi,

I've stumbled across an issue when using an empty string for the text
```r
gridtext::richtext_grob('')
```
yields
```
Error: '' does not exist in current working directory ('/home/lepennec/devel/ggwordcloud').
```

Thanks for the tremendou work...

**Comment by clauswilke** [comment]
Thanks! That's actually an xml2 bug, and maybe should be fixed there rather than having gridtext try to work around it.

``` r
library(xml2)
xml2::read_html("")
#> Error: '' does not exist in current working directory ('/private/var/folders/b1/13gn4j655jddkfhxmtk5tsfm0000gn/T/RtmpUchYvm/reprex442a65a1f71e').
```

<sup>Created on 2020-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by clauswilke** [comment]
Actually, I think there's a straightforward and safe way to fix this in gridtext, so I'll do that.

**Comment by clauswilke** [comment]
This should work now. Could you install the development version and test whether it works in the context in which you experienced the problem?

``` r
gridtext::richtext_grob("")
#> richtext_grob[GRID.richtext_grob.6]
gridtext::textbox_grob("")
#> textbox_grob[GRID.textbox_grob.7]
```

<sup>Created on 2020-02-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lepennec** [comment]
Wow! That was fast! This is now working as expected.
